# Generated by Django 3.2.4 on 2021-07-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.ImageField(upload_to='cover', verbose_name='image')),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
        migrations.CreateModel(
            name='ExpertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image', verbose_name='image')),
                ('job_expert', models.CharField(max_length=15, verbose_name='job_expert')),
                ('short_description', models.TextField(verbose_name='short_description')),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_description', models.TextField(verbose_name='short_description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='first_name',
            field=models.CharField(default='test', max_length=50, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='last_name',
            field=models.CharField(default='test', max_length=50, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
