# Generated by Django 3.2.4 on 2021-07-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210708_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='short_description',
        ),
    ]
