# Generated by Django 3.2.4 on 2021-07-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_authormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('job', models.CharField(max_length=50, verbose_name='job')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.DeleteModel(
            name='AuthorModel',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pricemodel',
            name='short_description',
        ),
    ]
