# Generated by Django 3.2.4 on 2021-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20210709_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.FloatField(verbose_name='price')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'price tip',
                'verbose_name_plural': 'price tips',
            },
        ),
    ]
