# Generated by Django 3.2.4 on 2021-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='banner'),
        ),
    ]
